plugin_blacklist: []
# # common
# - safety_area
# # extras
# - image_pub
# - vibration
# - distance_sensor
# - rangefinder
# - wheel_odometry
# - 3dr_radio
# - actuator_control
# - adsb
# - altitude
# - cam_imu
# - camera
# - command
# - companion_process_status
# - debug_value
# - esc_status
# - odom
# - esc_telemetry
# - fake_gps
# - ftp
# - geofence
# - global_position
# - 


plugin_whitelist:
- imu
#- 'sys_*'